### ISSUE TITLE
set <link rel="alternate"> in <head>

### ISSUE THREAD

**Issue by rettinghaus** [Edirom/WeGA-WebApp#121]
In page.html sollte `<html>` ein `@lang` tragen und im `<head>` ein entsprechendes `<link rel="alternate" href="xx" hreflang="yy">` mit Verweis auf die andere Sprachfassung.

**Comment by peterstadler** [comment]
Ja, nochmal vielen Dank.
Habe zuerst #122 gesehen und dort kommentiert …

**Comment by rettinghaus** [comment]
Zwei "alternate-links" konsolidieren die Google-Suche nicht, Ergebnisse tauchen weiterhin doppelt auf:
https://www.google.de/search?q=Bonham+%26+Sons,+W.+%26+F.+C.+site:www.weber-gesamtausgabe.de

Vergleiche *Bach digital* mit aktuell vier Sprachfassungen: 
https://www.google.de/search?q=BWV+1024+site%3Awww.bach-digital.de
