### ISSUE TITLE
missing attributes in <a> to alternate language version

### ISSUE THREAD

**Issue by rettinghaus** [Edirom/WeGA-WebApp#122]
Der Link zur anderen Sprachfassung sollte auch ein `@hreflang` und ein `@rel="alternate"` tragen.

**Comment by peterstadler** [comment]
Ja, vielen Dank!
Wenn ich das richtig sehe, dann sollte ich das nicht nur bei der Sprachumschaltung (am `<a>`) angeben, sondern auch bei der sitemap und als `<link>`-Element im Header.

siehe https://support.google.com/webmasters/answer/189077?hl=de
und https://www.ranking-check.de/blog/hreflang-die-5-haeufigsten-fehler-und-hall-of-fame/
und https://www.sistrix.de/hreflang-guide/
