### ISSUE TITLE
Grab related letters via correspSearch (csLink)

### ISSUE THREAD

**Issue by peterstadler** [Edirom/WeGA-WebApp#147]
see e.g. "Briefnetz erkunden" at http://avhr.bbaw.de/briefe/detail.xql?id=prov_syf_1cn_rt

**Comment by StefanDumont** [comment]
+1 ;-) 

Vielleicht auch zusätzlich noch die klassische Beacon-Anbindung beim Personenregistereintrag (vgl. http://avhr.bbaw.de/register/personen/detail.xql?id=prov_em3_3sd_ms ("Links zu externen Websites")). In der WeGA "PND Beacon Links".

**Comment by peterstadler** [comment]
Da gibt es jetzt auch so ein nettes Widget ;)
* https://dhd-blog.org/?p=10632
* https://github.com/correspSearch/csLink

**Comment by StefanDumont** [comment]
Sehr cool! Wenn Ihr auf Probleme stößt oder noch Feature-Wünsche habt, meldet euch! :-)
