### ISSUE TITLE
print roleName after forename on "What happened …"

### ISSUE THREAD

**Issue by rettinghaus** [Edirom/WeGA-WebApp#148]
Unter "Was geschah am …" sollten Personennamen, die `<roleName>` enthalten, so wiedergegeben werden, wie in `<persName>` formatiert, also statt "Erzherzogin von Österreich Henriette" besser  "Henriette, Erzherzogin von Österreich".

**Comment by peterstadler** [comment]
Ja, stimmt – besten Dank für die Meldung!
