### ISSUE TITLE
app element not formatted 

### ISSUE THREAD

**Issue by rettinghaus** [Edirom/WeGA-WebApp#153]
Innerhalb von `<app>` gibt es keine Formatierung von `<lem>` und `<rdg>`, sodass Inhalte doppelt ausgegeben werden.  Siehe: 
http://weber-gesamtausgabe.de/de/A002068/Korrespondenz/A041743.html

**Comment by peterstadler** [comment]
Ist bereits gefixt durch 789dd3a61cf95f5f4a5482fd0a35de3127c54b91 und wird sich im nächsten Release finden :)
