### ISSUE TITLE
Werke-Einzelansicht

### ISSUE THREAD

**Issue by peterstadler** [Edirom/WeGA-WebApp#169]
* URLS-Rewriting
* Popover

**Comment by peterstadler** [comment]
duplicate of #67

**Comment by peterstadler** [comment]
- [ ] Metadata
- [ ] Hide Sources for production

**Comment by CharleneJakob** [comment]
Werkansicht muss auf jeden Fall in Kopfleiste: Titel, Gattung, Autoren, WeV/op enthalten; Widmungsempfänger in Folgezeilen
