### ISSUE TITLE
correspContext not available in XML?

### ISSUE THREAD

**Issue by StefanDumont** [Edirom/WeGA-WebApp#199]
The correspContext is displayed but not available in the XML. Is this intended or a bug?

**Comment by peterstadler** [comment]
The current implementation is incomplete …
While the (ODD) schema supports the ```<correspContext>``` element in the TEI documents (see e.g. A041051), the WebApp does not care and simply computes the individual letter context. 

I will take this issue as a reminder to fix the WebApp to acknowledge the ```<correspContext>``` element in the TEI documents! 
Thanks!
