### ISSUE TITLE
Verlinkung in Navigation der Website

### ISSUE THREAD

**Issue by krHERO** [Edirom/WeGA-WebApp#202]
wenn ich auf weber --> schriften klicke, öffnet sich webers kopf mit basisdaten und darunter das submenü mit den verschiedenen materialarten, von denen dann "schriften" heller abgesetzt ist. jetzt kann ich in diesem submenü ganz unproblematisch zwischen tagebücher, werke usw navigieren. wenn ich aber versuche von dieser schon geöffneten "schriften" seite, auf die ich anfangs gesprungen bin, im obermenü weber-->tagebücher (ebenso die anderen einträge dort) anzuklicken, passiert nix (firefox browser), obwohl in der adresse oben schon .html#diaries drinsteht)
![verlinkunginnavigationderwebsite](https://user-images.githubusercontent.com/5928917/29821482-62e552b8-8cc8-11e7-9a16-581c5c906dd7.png)

**Comment by peterstadler** [comment]
Hier scheint eine mögliche Lösung genannt: https://stackoverflow.com/questions/680785/on-window-location-hash-change

**Comment by peterstadler** [comment]
postponed till bootstrap4
