### ISSUE TITLE
ADB/NDB doesn't work

### ISSUE THREAD

**Issue by rettinghaus** [Edirom/WeGA-WebApp#211]
Die Abfrage der ADB bzw. NDB funktioniert derzeit nicht. 

Die Reihenfolge in der Dokemnten-Liste rechts ist: 
`GND Eintrag` `NDB` `ADB` `GND Beacon Links`
Sinnvoller wäre m.E.: 
`ADB` `NDB` `GND Eintrag` `GND Beacon Links`

**Comment by peterstadler** [comment]
Lieber Klaus, 
die Abfrage der ADB und NDB wurde schon in 768ada056b1304d8489ed07805a923d0f6958242 gefixt, allerdings noch nicht veröffentlicht … wenn Du aber explizit fragst, dann mache ich das natürlich umgehend – schon fertig ;)

Die Anregung der Umsortierung nehme ich ebenfalls gerne auf, besten Dank!
