### ISSUE TITLE
Anzeige - App und Reading (A030798)

### ISSUE THREAD

**Issue by CharleneJakob** [Edirom/WeGA-WebApp#212]
Bezieht sich auf den Text A030798

1. 	Anzeige im Tooltip: wenn etwas nicht vorhanden ist, sowohl im Lemma als auch im Reading → wie soll das verbalisiert werden

2.	Anzeige im Tooltip: im Lemma ist Text gesperrt geschrieben, im Reading nicht → bessere Anzeige? Sonst nur durch betrachten des Lemmas nachzuvollziehen

3.	Anzeige im Text: Absätze, die im Reading aber nicht im Lemma enthalten sind (kurz vor Ende des Textes) → App „hängt in der Luft“

4.	sic hervorhebeben → im Reading schon korrigiert aufgeführt, für den „normalen“ Leser nicht nachzuvollziehen, dass das ursprünglich ein Fehler war?

5.	Anzeige im Tooltip bei notes: vorher angegebene Textstellen beziehen das Reading bzw. die notes mit ein, etwas verwirrend? (Bei der Stelle: [...] Mond- und Sternenbild in weiterer [app] Entfernung den Hintergrund bildete? [note] – [note] Das hierzu usw.)

**Comment by jakosch** [comment]
zu 1.) Beispielstelle im Quelltext:
```
<app>
    <lem wit="#wit-muse">
        <ref target="#footnote02" type="footnoteAnchor">*)</ref>
        <footNote xml:id="footnote02">*) Es ist anjetzt die zweite, wenig veränderte Auflage unter der Presse.</footNote>
    </lem>
    <rdg wit="#wit-az1"/>
</app>
```
Mögliche Lösung: wenn `<rdg>` leer, dann: "Keine Lesart in anderer Quelle."

**Comment by jakosch** [comment]
2.) kann ich gerade nicht nachvollziehen
3.) ist mMn. auch kein Problem.

**Comment by jakosch** [comment]
4.) Wieso hier in diesem Fall überhaupt korrigieren?

**Comment by peterstadler** [comment]
Bei unserer heutigen Telefonkonferenz haben @jakosch und ich beschlossen:

1. ergänzt @jakosch, siehe c5e5bc3826aa993dc7fecfec1facead995c7e7d2 
2. steht in keinem Verhältnis von Aufwand und Nutzen. 
3. das "in-der-Luft-hängen" finden wir nicht so schlimm, stellt das doch den leeren (bzw. nicht vorhandenen) Absatz dar. Alternative Lösungen scheinen vom Aufwand-Nutzen-Verhältnis aktuell unangebracht.
4. da kümmert sich @peterstadler 
4. kümmert sich ebenfalls @peterstadler

**Comment by peterstadler** [comment]
### aktueller Stand

1. scheint aktuell nicht zu funktionieren (trotz c5e5bc3) @jakosch 
2. noch in Arbeit, siehe #311 
3. wontfix, bleibt so
4. sic ist jetzt die Standardausgabe, siehe 08062874057e6ef47f6c75ccc441556d0f253370, daher kann das als 'fixed' gelten
5. fixed by 02273c15c70b4a3055117c97c4bb91fe565ebebb

**Comment by jakosch** [comment]
Hast du mal im branch 212 geschaut?

**Comment by peterstadler** [comment]
1. branch 212 ist aktualisiert und gemergt
2. done
3. wontfix
4. done
5. done
