### ISSUE TITLE
add document type filter to document backlinks

### ISSUE THREAD

**Issue by peterstadler** [Edirom/WeGA-WebApp#217]
the document type filter is currently only available on person backlinks …

**Comment by jakosch** [comment]
How should this look like? Where should the filter be placed: In an extra column or somewhere on the right side? 
![image](https://user-images.githubusercontent.com/4886121/58374431-67578680-7f3e-11e9-9188-533aba90f1e6.png)

**Comment by peterstadler** [comment]
@jakosch and I discussed the issue today and decided not to implement since it would involve too much effort for not so much benefit (backlinks for documents are usually less than 10)
