### ISSUE TITLE
source="Bach" prosopographies should link to "Bach Digital"

### ISSUE THREAD

**Issue by peterstadler** [Edirom/WeGA-WebApp#24]

**Comment by rettinghaus** [comment]
Best feature in upcoming release :+1:

**Comment by peterstadler** [comment]
@rettinghaus könntest Du mir nochmal den genauen Link und Textvorschlag geben? Danke!

**Comment by rettinghaus** [comment]
Bis die Daten drin und über PND-Resolver erreichbar sind, einfach: http://www.bach-digital.de/
Als Text vielleicht *Datenübernahme aus Bach digital*?
