### ISSUE TITLE
Apparat restrukturieren

### ISSUE THREAD

**Issue by jakosch** [Edirom/WeGA-WebApp#258]
Ideen: 
* Oberkategorien
* Zusammenfassung ähnlicher oder zusammengehörender Informationen
* Bessere visuelle Trennung durch Gewichtung der Überschriften oder Reduktion dieser

Zum testen: A042752, A040313, A042329

**Comment by peterstadler** [comment]
* Ausblenden nicht-vorhandener Informationen (siehe z.B. Textkonstitution und Einzelstellenerläuterung in A065665; oder Generalvermerk in A043439)

**Comment by jakosch** [comment]
Ausblenden von Zwischenüberschriften (z.B. "Generalvermerk") geht nur, wenn man die Information mit ins map nimmt (und dann im Template abfragt über `app-shared:if-exists`) oder die Überschrift mit in die Funktion (in dem Fall `app:print-generalRemark`) nimmt. Was ist dir lieber/fällt dir noch ein anderer Weg ein?

**Comment by peterstadler** [comment]
+1 für Informationen mit in die `$model` map nehmen und dann über `app-shared:if-exists` abfragen

**Comment by peterstadler** [comment]
Weiß nicht, ob wir das auch schon thematisiert hatten, aber es gibt auch noch Handschriften, die in Fragmenten vorliegen. Beispiele sind [A041993](https://weber-gesamtausgabe.de/de/A002068/Korrespondenz/A041993.html#bs-tab-editorial), [A041998](https://weber-gesamtausgabe.de/de/A002068/Korrespondenz/A041998.html#bs-tab-editorial) oder [A042001](https://weber-gesamtausgabe.de/de/A002068/Korrespondenz/A042001.html#bs-tab-editorial) …

**Comment by jakosch** [comment]
Weiteres todo: "Textkonstitution" ausblenden, wenn leer

dazu evtl: xpath in 'createApparatus` checken

**Comment by jakosch** [comment]
Weitere Idee: Direktlink zur entsprechenden Stelle bei Textkonstitution und Einzelstellenerläterung

dazu nötig: ref-ID und `$('a[href="#transcription"]').tab('show');` o.ä.
