### ISSUE TITLE
Seitenleiste ("Dokument") ausblenden, wenn keine Auswahl vorhanden

### ISSUE THREAD

**Issue by jakosch** [Edirom/WeGA-WebApp#288]
siehe z.B. `/de/Projekt/Editionsrichtlinien_Text/chap-IN.html`

**Comment by peterstadler** [comment]
Ok, warte, das sollten wir nochmal durchsprechen. Ich hatte vermutlich(?) schon die Idee, dass man zumindest die XML-Vorschau (und den Download?) da wieder unterbringt. Auch kann man überlegen, ob man vielleicht "erwähnte Elemente" (analog zu den erwähnten Personen etc.) in der rechten Spalte unterbringt.  
Jedenfalls wollte ich diese Spalte nicht auflösen und ein neues Layout einführen – es sei denn, Du überzeugst mich :)

Da sollten wir nochmal brainstormen …

**Comment by jakosch** [comment]
Das Ticket ist ja schon etwas älter. Wenn es dort wieder eine Auswahl gibt, ist das natürlich hinfällig.
