### ISSUE TITLE
fix hover color in filter

### ISSUE THREAD

**Issue by jakosch** [Edirom/WeGA-WebApp#290]

**Comment by peterstadler** [comment]
Can you elaborate a little bit on what you're trying to do? I notice the transparent background for the filter but the color is not changed (see "Mainz" screenshot).
![Bildschirmfoto 2019-03-26 um 12 39 43](https://user-images.githubusercontent.com/2247936/54994340-503efb80-4fc4-11e9-972b-056761ca8748.png)

**Comment by jakosch** [comment]
My mistake. Please recheck.
