### ISSUE TITLE
Guidelines Element-/Attributseiten

### ISSUE THREAD

**Issue by jakosch** [Edirom/WeGA-WebApp#293]
### Ideen / Fragen
- [x] font-family sans-serif
- [x] Hierachieebenen / Labelkennzeichnung
- [x] handling von `<p>`

**Comment by peterstadler** [comment]
### Weitere Aufhübschungen für die Spec-Seiten:

Das, was aktuell bei Attributen unter "Status" läuft könnte man aus dieser Zeile rauslösen und entweder als Icon oder als einfachen Text hinter (oder unter) dem Attributnamen unterbringen. Mögliche Werte sind dort (im ODD) sind `rec`, `req` und `opt`, siehe auch https://github.com/Edirom/WeGA-WebApp/blob/e55cd25d5cdc26a76ee6e7defb919cf4de7aa1aa/catalogues/dictionary_de.xml#L530-L532
