### ISSUE TITLE
display examples within attDef

### ISSUE THREAD

**Issue by peterstadler** [Edirom/WeGA-WebApp#296]
Currently, `<exemplum>` within `<attDef>` are not being processed? See e.g. our spec page for `<seg>` which features several examples for `@type` in the ODD file (starting line 15633 in https://github.com/Edirom/WeGA-ODD/blob/develop/compiled-ODD/guidelines-de-wega_all.compiled.xml)

An example from the TEI Guidelines with examples for attributes is [`node`](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-node.html)

**Comment by peterstadler** [comment]
Hmm, `<title>` features the `<exemplum>` from `@xml:lang` properly. Maybe only `<teix:egXML>` are processed but not the parent `<exemplum>`? Or only `exemplum[teix:egXML]`?

**Comment by jakosch** [comment]
simple fix: remove `@xml:lang` condition in the respective map in `gl:spec-details`? 
`'examples' := $spec/tei:exemplum ! gl:print-exemplum(.)` ?
