### ISSUE TITLE
popover title localization

### ISSUE THREAD

**Issue by jakosch** [Edirom/WeGA-WebApp#301]
Zu bearbeitender Code in `apparatus.xsl`: 
```
         <xsl:attribute name="data-title">
            <xsl:value-of select="local-name()"/>
         </xsl:attribute>
``` 

Vorhandene Titel:
`app`
`note` `(type 'commentary', 'definition', 'textConst', 'thematicCom', 'summary', 'editorial', 'incipit')`
`subst`
`add`
`gap` `(reason 'illegible', 'outofScope')`
`del` 
`sic`
`choice`

**Comment by peterstadler** [comment]
build is broken, need to check and probably update expected results?!

**Comment by jakosch** [comment]
fixed in current develop
