### ISSUE TITLE
sensible layout for rdg/app popovers

### ISSUE THREAD

**Issue by jakosch** [Edirom/WeGA-WebApp#302]
This is not very legible

![image](https://user-images.githubusercontent.com/4886121/58733106-cd875200-83f3-11e9-9dfa-7c94ceef5722.png)

**Comment by jakosch** [comment]
Idee

![image](https://user-images.githubusercontent.com/4886121/59164267-3153fe00-8b0b-11e9-9ec9-c91309bc4d8a.png)

**Comment by jakosch** [comment]
Oder bei Lesarten vielleicht so etwas:

![image](https://user-images.githubusercontent.com/4886121/59555670-57b7e480-8fb6-11e9-9270-03dc8dc0f692.png)

In diesem Zusammenhang @peterstadler: Brauchen wir ein extra Issue für die Bezeichnung/Handhabung von Quellen in diesem Zusammenhang?

**Comment by peterstadler** [comment]
Das letzte Beispiel findet sehr viel Beifall 👏

**Comment by peterstadler** [comment]
Problem für die Zuordnung von Lesarten zu Textzeugen besteht aktuell darin, dass nur der `tei:body` übergeben wird und damit nicht auf die `tei:sourceDesc` zugegriffen werden kann, siehe https://github.com/Edirom/WeGA-WebApp/blob/597add6d3b170fb0e2b193ca375c1639ba076408/modules/app.xqm#L1268

**Comment by jakosch** [comment]
> Problem für die Zuordnung von Lesarten zu Textzeugen besteht aktuell darin, dass nur der `tei:body` übergeben wird und damit nicht auf die `tei:sourceDesc` zugegriffen werden kann, siehe
> 
> https://github.com/Edirom/WeGA-WebApp/blob/597add6d3b170fb0e2b193ca375c1639ba076408/modules/app.xqm#L1268

ab jetzt in #307

**Comment by peterstadler** [comment]
Verbesserungen sind implementiert :)
