### ISSUE TITLE
add pointer to backlinks for revealed letters

### ISSUE THREAD

**Issue by peterstadler** [Edirom/WeGA-WebApp#304]
At Berlin f2f 2019 we decided to add a note with pointer to the backlinks tab like 
```html
<p class="notAvailable">Erschlossene Korrespondenz (siehe <a href="#backlinks">Rückverweise</a>). Text nicht nachweisbar. Für weitere Informationen siehe  <a href="#editorial">Apparat</a>.</p>
```

see e.g. A045261

Most probably, there need to be some adjustments made to the javascript but the link to the editorial should serve as a proper model.

**Comment by jakosch** [comment]
JavaScript ist trivial. Die Klammerschachtelung führt allerdings aufgrund des einzufügenden HTML-Tags zu dieser etwas ungelenken Konstruktion (und zusätzlich zwei Wörterbucheinträge): 
```
    if($doc//tei:correspDesc[@n = 'revealed']) then (
        lang:get-language-string('correspondenceRevealed', $lang), ' ',
        <span>({lang:get-language-string('see', $lang)}</span>, ' ',
        <span><a href="#backlinks">{lang:get-language-string('backlinks', $lang)}</a>).</span>, ' ',
        lang:get-language-string('textNotAvailable',$lang) )
```
