### ISSUE TITLE
Zuordnung von Quellen (rdg und Apparat)

### ISSUE THREAD

**Issue by jakosch** [Edirom/WeGA-WebApp#307]
Problembeschreibung siehe https://github.com/Edirom/WeGA-WebApp/issues/302#issuecomment-509517599_  

Problem für die Zuordnung von Lesarten zu Textzeugen besteht aktuell darin, dass nur der `tei:body` übergeben wird und damit nicht auf die `tei:sourceDesc` zugegriffen werden kann, siehe https://github.com/Edirom/WeGA-WebApp/blob/597add6d3b170fb0e2b193ca375c1639ba076408/modules/app.xqm#L1268

Testbeispiele: `A042284`, `A042246`

**Comment by jakosch** [comment]
Workaround: `@wit` als Sigel verwenden und auch im Apparat ausgeben? 
![image](https://user-images.githubusercontent.com/4886121/61563349-f7fc9f80-aa73-11e9-86e7-6b006821619a.png)

![image](https://user-images.githubusercontent.com/4886121/61563368-021e9e00-aa74-11e9-89e7-d5dbef610fbe.png)

**Comment by jakosch** [comment]
Oder nur die Quellen extra mitgeben? `default return $doc//(tei:text/tei:body | tei:listWit)` 
Könnte es da anderswo zu Komplikationen kommen?

**Comment by peterstadler** [comment]
Der Teil mit dem Mitgeben der Quellen ist m.E. gelöst, allerdings ist doch nicht immer die erste Quelle die Grundlage der Edition. Wenn die erste Quelle "verschollen" oder "Verbleib unbekannt" ist, dann rückt die zweite Quelle nach …

**Comment by peterstadler** [comment]
Wenn das Lemma ein `@wit` hat, dann sollte das auch Vorrang bekommen, siehe A030798

**Comment by peterstadler** [comment]
witness mit `@rend="lost|non-accessible"` können grundsätzlich nicht die Hauptquelle sein.

**Comment by peterstadler** [comment]
Wenn möglich, bitte die `listWit` auch in die XSL Parameter verschieben, siehe https://github.com/Edirom/WeGA-WebApp/blob/747146db27bd55cd30c8c133d3020f39e3d93732/modules/app.xqm#L1285-L1287

**Comment by peterstadler** [comment]
cherry-picked into develop branch, closing!
