### ISSUE TITLE
backlink apparatus entries to context in transcription

### ISSUE THREAD

**Issue by jakosch** [Edirom/WeGA-WebApp#310]

**Comment by jakosch** [comment]
![out](https://user-images.githubusercontent.com/4886121/62416350-5eb7b680-b639-11e9-9559-73dd64575023.gif)

**Comment by jakosch** [comment]
strange bug: duplicate links 

![image](https://user-images.githubusercontent.com/4886121/62416356-945c9f80-b639-11e9-91c5-2f667c653e66.png)

**Comment by peterstadler** [comment]
included in 39b2ef38d13f3f028fdbc6562732007367e308b9
