### ISSUE TITLE
use human-readable title in breadcrumbs on var pages

### ISSUE THREAD

**Issue by jakosch** [Edirom/WeGA-WebApp#325]
nobody cares about the document ID ...
![image](https://user-images.githubusercontent.com/4886121/68691344-e2a40780-0573-11ea-9839-119c49a00cea.png)

**Comment by peterstadler** [comment]
Hmm, titles can get very long (and are displayed just above the breadcrumb). Yet, for persons there's already the name displayed in the breadcrumb (rather than the ID)

**Comment by peterstadler** [comment]
@jakosch and I decided to beautify the breadcrumbs for (project related) pages like "Bandübersicht", "Kontakt", etc. but not for documents from the edition.
