### ISSUE TITLE
Swagger UI: hide unused tags and definitions

### ISSUE THREAD

**Issue by peterstadler** [Edirom/WeGA-WebApp#326]
that's "correspondence" and "svnHistoryPatch" in our case.
It was hidden in the old Swagger UI so expect there to be a switch/parameter somewhere in the swagger config/init. If not, we can safely remove those two objects.

**Comment by jakosch** [comment]
mit `defaultModelsExpandDepth` auf `-1` kann man die gesamte Models-Abteilung ausblenden.
Ansonsten sind ungenutzte Abschnitte offenbar nicht vorgesehen? 
https://github.com/swagger-api/swagger-ui/issues/3819

**Comment by peterstadler** [comment]
ok, I'll remove those objects from the swagger.json file
