### ISSUE TITLE
Herausgeber-Ergänzung in eckigen Klammern (Briefe)

### ISSUE THREAD

**Issue by ran-mo** [Edirom/WeGA-WebApp#38]
**Frage**, ob Ergänzungen nicht doch auch in eckiger Klammer bleiben könnten?: 
**Entscheidung**: Herausgeber-Ergänzungen werden in eckigen Klammern dargestellt und in der Liste unter dem Text auch nicht mit ausgeworfen (und im Text nicht mit Sternchen versehen)
	Rubriken wie in den Richtlinien-Empfehlungen:

**Comment by peterstadler** [comment]
done.
