### ISSUE TITLE
improve cmif export for new harvester

### ISSUE THREAD

**Issue by peterstadler** [Edirom/WeGA-WebApp#392]
as requested by @StefanDumont per email:

> Der Harvester checkt aufgrund der Menge der Daten, ob die Datei verändert wurde. Das macht er a) anhand eines Since-Modified-HTTP-Requests (das geht sehr schnell) und b) anhand des Datums in publicationStmt. Könntet ihr zumindest letzteres jeweils auf das Datum der letzten tatsächlichen Aktualisierung (=Veröffentlichung eurer jeweiligen Version) setzen? Das würde uns sehr helfen, weil wir so schwer erkennen können, ob sich was verändert hat.
Noch besser wäre natürlich, wenn das direkt per HTTP Header laufen könnte.

**Comment by StefanDumont** [comment]
Ah, super cool! Vielen Dank! Und ein gutes neues Jahr noch!
