### ISSUE TITLE
Erweiterung der Suchfunktionen

### ISSUE THREAD

**Issue by obertsalome** [Edirom/WeGA-WebApp#417]
**Registersuche/Briefe**

- Filter einfügen für
- [ ] erwähnte Personen
- [ ] erwähnte Orte
- [ ] Schlagwörter (?)

**Comment by riedde** [comment]
Nebenbei: Wurde schon einmal darüber nachgedacht diesen Filter, der ja bereits jetzt sehr umfangreiche Funktionalitäten bietet, etwas zu entschlacken? Bspw. zwei Filter-Modi anzubieten, einen einfachen und einen Experten-Modus?

Grundsätzlich halte ich die Idee auch nach ausgezeichneten Entitäten suchen/filtern zu können, für sehr hilfreich. Dennoch möchte ich die Frage in den Raum stellen, ob es sich hierbei um eine Filter-Funktion handelt, oder ob das nicht auch Teil einer erweiterten/Experten-Suche sein könnte.

**Comment by peterstadler** [comment]
Die beiden Filter "erwähnte Orte" und "erwähnte Werke" sind bei allen anderen Listen (wo diese Informationen in den Daten enthalten sind) verfügbar, nur bei der Korrespondenz nicht. Das ist wohl einfach ein Versehen, welches ich gleich beheben werden.

"Schlagwörter" haben wir nur bei den Dokumenten vergeben, daher ist das auch die einzige Listenansicht mit diesem Filter.

Was @riedde's Frage nach einem Experten-Modus angeht. Ich bin da etwas skeptisch bei so einer binären Opposition (Experte/Laie), einerseits wegen der impliziten Wertung, andererseits da m.E. dieses (Frontend)Paradigma überholt ist zugunsten einer grundsätzlicheren Flexibilisierung. Wie das umzusetzen ist in der WeGA-WebApp sollten wir gerne mal besprechen ;) Ein allererster Ansatz findet sich unter #419

**Comment by riedde** [comment]
Danke @peterstadler für dienen Kommentar! Ich gebe dir recht, diese Opposition ist überholt. Anders formuliert meinte ich damit die Trennung in Allgemeine Überblicksinfos und eine Detailansicht. (Quasi wie bei digitalen Taschenrechnern, bei denen es den "normal" und den "wissenschaftlichen" Modus gibt.) Ich schaue mir gerne die verlinkten Issues und PRs an und melde mich dann wieder :)
