### ISSUE TITLE
Improve work preview

### ISSUE THREAD

**Issue by rettinghaus** [Edirom/WeGA-WebApp#430]
1. The work view shows an "portrait" image with the title _no portrait available_.  As this doesn't make sense, this could and should be slightly improved. 

And to be honest: the image itself look more like Smurf feet than notes …
![](https://weber-gesamtausgabe.de/resources/img/icons/icon_musicalWorks_gross.png)

2. Show more structural metadata. The roles of persons often are not distinguishable, so something like "Lyrics by XXX" would be appreciated (see https://weber-gesamtausgabe.de/de/A002068/Werke/A020371.html).

**Comment by peterstadler** [comment]
Hi @rettinghaus, full ack, the work preview needs to be improved. I will get in touch with our design team for an improved preview icon ;) 

Regarding your second issue: while there is some data that we do not output at present in the HTML view (e.g. from `<scoreDef>` and `<perfMedium>`), the responsibilities and roles are presented to the user. 
![Bildschirmfoto 2022-10-10 um 11 14 52](https://user-images.githubusercontent.com/2247936/194833931-2b4fd663-6d2e-44cf-830c-8dd7930b2ae9.png)
![Bildschirmfoto 2022-10-10 um 11 15 33](https://user-images.githubusercontent.com/2247936/194833944-8c5a82e4-c921-415a-9b39-2b1376481cb8.png)

Or do I miss something?

**Comment by rettinghaus** [comment]
Well, yes. Sorry for being imprecise here. In the lower "Information about the work" block below the "Dedicatees" / "Widmung an" header follows a long list of names without further information. This suggests that the work is dedicated to all of those, which looks suspiciously wrong.

**Comment by peterstadler** [comment]
Had to look this up to be sure but indeed these are all dedicatees. See the title page: https://digital.slub-dresden.de/werkansicht/dlf/123945/1 "… Den Dichtern in Achtung und Liebe zugeeignet | vom Tonsetzer…"

**Comment by rettinghaus** [comment]
Oh, that was unexpected. Thanks for looking into this!

**Comment by peterstadler** [comment]
Getting back to this and for the record:
1. I'm postponing the face lift of the works icon until we work on the display of the object type "sources". This is very much related to the works category so we might come up with something for both.
2. I will change the "no portrait available" tooltip to something better (or even remove it completely)
