### ISSUE TITLE
XML preview broken

### ISSUE THREAD

**Issue by rettinghaus** [Edirom/WeGA-WebApp#436]
XML-Preview loses all xml tags!

![image](https://user-images.githubusercontent.com/7693447/214587740-8b11eca6-d73b-4b2f-9836-f343bb2424e6.png)

**Comment by peterstadler** [comment]
Thanks for reporting! That seems to be some sort of regression in the new eXist v6.1.0, see https://github.com/eXist-db/exist/issues/4702 
I have a workaround in place but will reset our production service to eXist 6.0.1 until the next WeGA release.

**Comment by peterstadler** [comment]
deployment at main site weber-gesamtausgabe.de is fixed now.
