### ISSUE TITLE
Add full text URL to CMIF v2

### ISSUE THREAD

**Issue by peterstadler** [Edirom/WeGA-WebApp#445]
as requested by @StefanDumont. The implementation might look like

```xml
<correspDesc>
 <note>
  <ref type="cmif:fulltext" target="https://edition-humboldt.de/H220020.xml" />
 </note>
</correspDesc>
```

NB, that feature is yet undocumented and the terminology is subject to change.

**Comment by StefanDumont** [comment]
The proposed terminology at the moment is: cmif:isAvailableAsTEIfile, see https://lod.academy/cmif/vocab/terms/#isAvailableAsTEIfile
