### ISSUE TITLE
Numbers of chapters in editorial guidelines (text and music) is not displayed correctly

### ISSUE THREAD

**Issue by obertsalome** [Edirom/WeGA-WebApp#456]
Every chapter is named as chapter 1

![Bildschirmfoto 2024-04-23 um 10 15 06](https://github.com/Edirom/WeGA-WebApp/assets/43742700/c2265ae5-8a1b-4060-a5ad-ee5c583b62d9)

**Comment by peterstadler** [comment]
Just checked: this bug was introduced with the removal of the `xml:lang` information from the TEI data. I will add a workaround to the processing …
