### ISSUE TITLE
suppress empty date elements for CMIF export

### ISSUE THREAD

**Issue by peterstadler** [Edirom/WeGA-WebApp#482]
The [CMIF Checker](https://correspsearch.net/api/v2.0/services/check/index.xql?url=https%3A%2F%2Fweber-gesamtausgabe.de%2Fcmif_v2.xml) revealed several empty tei date elements with only a `<date cert="unknown"/>`.

**Comment by riedde** [comment]
I suppressed another date output. Just FYI: https://github.com/Henze-Digital/HenDi-WebApp/blob/db4af4f8ee41f7346f774e090c6e0fb6776f750e/data/modules/cmif.xql#L166
